services:
  - type: web
    name: laravel-filament-app
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APP_ENV
        value: local
      - key: APP_DEBUG
        value: true
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mariadb
      - key: DB_HOST
        value: z8vpra.h.filess.io
      - key: DB_PORT
        value: 61000
      - key: DB_DATABASE
        value: epas_oncechoice
      - key: DB_USERNAME
        value: epas_oncechoice
      - key: DB_PASSWORD
        value: ec9af42aafc79b74c2571ddfe9f06921b56758c5
